---
- name: Install java in Amazon linux
  ansible.builtin.yum:
    name: '{{ java_package }}'
    state: present
  when: ansible_os_family == 'RedHat'
- name: Install java in Ubuntu linux
  ansible.builtin.apt:
    name: '{{ java_package_ubuntu }}'
    state: present
  when: ansible_os_family == 'Debian'
- name: Download SonarQube
  ansible.builtin.get_url:
    url: https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-{{ sonarqube_version }}.zip
    dest: /opt/
    mode: "0644"
- name: Extract SonarQube
  ansible.builtin.unarchive:
    src: /opt/sonarqube-{{ sonarqube_version }}.zip
    dest: /opt/
    remote_src: true
    creates: /opt/sonarqube-{{ sonarqube_version }}
- name: Rename SonarQube directory
  ansible.builtin.command: mv /opt/sonarqube-{{ sonarqube_version }} /opt/sonarqube
  args:
    creates: /opt/sonarqube
- name: Add sonar user
  ansible.builtin.user:
    name: sonar
    comment: Sonar Repository Manager
    shell: /sbin/nologin
    create_home: false
- name: Change ownership of Sonar directory
  ansible.builtin.file:
    path: /opt/sonarqube
    owner: sonar
    group: sonar
    recurse: true
- name: Replace the user to sonar user in the sonar.sh file
  ansible.builtin.lineinfile:
    path: /opt/sonarqube/bin/linux-x86-64/sonar.sh
    search_string: '#RUN_AS_USER='
    line: RUN_AS_USER=sonar
- name: Set up SonarQube as a service
  ansible.builtin.template:
    src: sonarqube.service.j2
    dest: /etc/systemd/system/sonarqube.service
    owner: sonar
    group: sonar
    mode: '0777'
- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true
- name: Restart sonarqube
  ansible.builtin.systemd_service:
    name: sonarqube
    state: restarted
